version: '3'

services:
  app:
    build: docker/app
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    environment:
      APP_APACHE_ROOT_DIR: /var/www/html
    ports:
      - 80:80