version: "3.9"

services:
  xebot:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./profiles.json:/App/profiles.json
      - ./profile_sessions.json:/App/profile_sessions.json